export const ADD_ACCOUNT_LIST = 'ADD_ACCOUNT_LIST';
export const DEL_ACCOUNT_LIST = 'DEL_ACCOUNT_LIST';
export const EDIT_ACCOUNT_LIST = 'EDIT_ACCOUNT_LIST';
export const INIT_ACCOUNT_LIST = 'INIT_ACCOUNT_LIST';

export const SEARCH_ACCOUNT_BY_ID = 'SEARCH_ACCOUNT_BY_ID';

export const ACCOUNT_TO_TOP = 'ACCOUNT_TO_TOP';

export const EDIT_FONT_SIZE = 'EDIT_FONT_SIZE';
export const INIT_FONT_SIZE = 'INIT_FONT_SIZE';
